-- Run in Supabase SQL Editor for the team's EXISTING schema.
-- Preserves projects/issues/profiles, column names, data, and existing RLS policies.
-- For Approve/Reject publishing, also run docs/supabase-review.sql afterwards.
begin;

alter table public.projects
  add column if not exists "DefaultBranch" text not null default 'main';
alter table public.issues
  add column if not exists expected_behavior text,
  add column if not exists screenshot_ref text;

-- Add automatic IDs only where the existing bigint PK has no identity/default.
-- Initialize new sequences above existing IDs instead of resetting existing ones.
do $$
declare
  v_table_name text;
  sequence_name text;
  maximum_id bigint;
begin
  foreach v_table_name in array array['projects', 'issues'] loop
    if exists (
      select 1 from information_schema.columns c
      where c.table_schema = 'public' and c.table_name = v_table_name
        and c.column_name = 'id' and c.is_identity = 'NO' and c.column_default is null
    ) then
      execute format('lock table public.%I in access exclusive mode', v_table_name);
      execute format('alter table public.%I alter column id add generated by default as identity', v_table_name);
      execute format('select max(id) from public.%I', v_table_name) into maximum_id;
      sequence_name := pg_get_serial_sequence(format('public.%I', v_table_name), 'id');
      perform setval(sequence_name::regclass, greatest(coalesce(maximum_id, 1), 1), coalesce(maximum_id >= 1, false));
    end if;
    sequence_name := pg_get_serial_sequence(format('public.%I', v_table_name), 'id');
    if sequence_name is not null then
      execute format('grant usage, select on sequence %s to service_role', sequence_name::regclass);
    end if;
  end loop;
end $$;

create table if not exists public.bob_jobs (
  id uuid primary key default gen_random_uuid(),
  issue_id bigint not null references public.issues(id),
  status text not null default 'QUEUED' check (status in (
    'QUEUED', 'CLONING', 'INVESTIGATING', 'FIXING', 'VALIDATING',
    'READY_FOR_REVIEW', 'NEEDS_HUMAN_INTERVENTION', 'FAILED'
  )),
  repo_url text not null,
  base_branch text not null,
  fix_branch text,
  bob_task_id text,
  result jsonb,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);
create index if not exists bob_jobs_issue_id_idx on public.bob_jobs(issue_id);
alter table public.bob_jobs enable row level security;
revoke all on public.bob_jobs from anon, authenticated;
grant select, insert, update on public.bob_jobs to service_role;
grant select on public.projects to service_role;
grant select, insert on public.issues to service_role;

-- Both inserts succeed together or roll back together. No orphaned issue on job failure.
-- Original ProjekId remains varchar; newer project_id schemas are supported.
-- No existing relation or status enum is changed.
create or replace function public.create_bob_issue_job(
  p_project_id bigint,
  p_title text,
  p_description text,
  p_expected_behavior text,
  p_screenshot_ref text,
  p_reporter_id text,
  p_category text,
  p_issue_status text
) returns jsonb
language plpgsql security invoker set search_path = ''
as $$
declare
  project_record public.projects%rowtype;
  new_issue_id bigint;
  new_job_id uuid;
begin
  select * into strict project_record from public.projects where id = p_project_id;
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'issues' and column_name = 'project_id'
  ) then
    execute $insert$
      insert into public.issues (
        project_id, reporter_id, title, description, category_issues, status,
        expected_behavior, screenshot_ref
      ) values ($1, $2, $3, $4, $5, 'reported', $6, $7)
      returning id
    $insert$ into new_issue_id
    using p_project_id, p_reporter_id, p_title, p_description, p_category,
      p_expected_behavior, p_screenshot_ref;
  else
  execute $insert$
  insert into public.issues (
    "ProjekId", "ReporterId", title, description, "CategoryIssues", "Status",
    expected_behavior, screenshot_ref
  ) values (
    $1::text, $2, $3, $4, $5, $6, $7, $8
  ) returning id
  $insert$ into new_issue_id
  using p_project_id, p_reporter_id, p_title, p_description, p_category, p_issue_status,
    p_expected_behavior, p_screenshot_ref;
  end if;

  insert into public.bob_jobs (issue_id, repo_url, base_branch)
  values (new_issue_id, project_record."RepoUrl", coalesce(nullif(project_record."DefaultBranch", ''), 'main'))
  returning id into new_job_id;

  return jsonb_build_object('issueId', new_issue_id::text, 'jobId', new_job_id);
end $$;

revoke all on function public.create_bob_issue_job(bigint,text,text,text,text,text,text,text)
  from public, anon, authenticated;
grant execute on function public.create_bob_issue_job(bigint,text,text,text,text,text,text,text)
  to service_role;
notify pgrst, 'reload schema';
commit;
